spring.application.name=crm-application

#server config
server.port = 8484

#database config
spring.datasource.url = jdbc:mysql://localhost:3306/telusko_db
spring.datasource.username =root
spring.datasource.password =myPwd@26

#JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect