spring.application.name=datajpa1crud
spring.datasource.url=jdbc:mysql://localhost:3306/telusko_db
spring.datasource.username=root
spring.datasource.password=myPwd@26
spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql= true

